#ifndef TN_GUESTBOOK_PROGRAM_H
#define TN_GUESTBOOK_PROGRAM_H

#include <thru-sdk/c/tn_sdk.h>

#define TN_GUESTBOOK_MAX_MESSAGE_LEN 256U

#define TN_GUESTBOOK_ERR_INVALID_INSTRUCTION_DATA_SIZE 0x2000UL
#define TN_GUESTBOOK_ERR_INVALID_INSTRUCTION_TYPE      0x2001UL
#define TN_GUESTBOOK_ERR_MESSAGE_TOO_LONG              0x2002UL
#define TN_GUESTBOOK_ERR_ACCOUNT_CREATE_FAILED         0x2003UL
#define TN_GUESTBOOK_ERR_ACCOUNT_ACCESS_FAILED         0x2004UL
#define TN_GUESTBOOK_ERR_ACCOUNT_SET_WRITABLE_FAILED   0x2005UL
#define TN_GUESTBOOK_ERR_ACCOUNT_RESIZE_FAILED         0x2006UL

#define TN_GUESTBOOK_INSTRUCTION_CREATE 0U
#define TN_GUESTBOOK_INSTRUCTION_POST   1U

typedef struct __attribute__((packed)) {
    ulong message_count;
    uint message_len;
    uchar message[TN_GUESTBOOK_MAX_MESSAGE_LEN];
} tn_guestbook_account_t;

#endif
