#ifndef TN_GUESTBOOK_PROGRAM_H
#define TN_GUESTBOOK_PROGRAM_H

#include <thru-sdk/c/tn_sdk.h>

#define TN_GUESTBOOK_MAX_MESSAGE_LEN 256U

#define TN_GUESTBOOK_ERR_INVALID_INSTRUCTION_DATA_SIZE 0x2000UL
#define TN_GUESTBOOK_ERR_INVALID_INSTRUCTION_TYPE      0x2001UL
#define TN_GUESTBOOK_ERR_MESSAGE_TOO_LONG              0x2002UL

#define TN_GUESTBOOK_INSTRUCTION_POST 1U

#endif
